baseURL = 'https://meashiri.github.io/ctf-writeups/'
languageCode = 'en-us'
title = 'CTF notepad'
theme = 'PaperMod'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page
ShowToc = true


[taxonomies]
  category = 'categories'
  tag = 'tags'


[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "My CTF notepad - hints, writeups and reflections"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	math = true
	ShowToc = true
	TocOpen = true
	ShowShareButtons = false
	ShowReadingTime = true
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = true
	ShowRssButtonInSectionTermList = false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/meashiri"


[markup.goldmark.renderer]
unsafe= true

# Main menu Items

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4
