baseURL: 'https://meashiri.github.io/ctf-writeups/'
languageCode: en-us
title: CTF notepad
theme: PaperModX
paginate: 12
ShowToc: true
googleAnalytics: G-JNJE77L6VW


taxonomies:
  category: categories
  tag: tags

params:
  mode: light
  useCDN: false
  subtitle: 'My CTF notepad - hints, writeups and reflections'
  mathjax: true
  katex: true
  math: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: true
  TocOpen: true
  TocSide: 'left'
  description: "My CTF writeups, links, learnings and reflections.                                                                 "
  cover.image: true
  images: ["meashiri-cover.png"]
  
  assets:
    favicon: "ashiri.svg"
    favicon16x16: "ashiri16x16.png"
    favicon32x32: "ashiri32x32.png"
    apple_touch_icon: "ashiri.svg"
    safari_pinned_tab: "ashiri.svg"
        
  homeInfoParams:
    Title: "Ashiri's CTF notepad"
    Content: "CTF challenges, solutions, tricks that may come in handy"
                                
  socialIcons:
    - name: github
      url: 'https://github.com/meashiri'
    - name: ctftime
      url: 'https://ctftime.org/user/18233'
    - name: Rss
      url: 'index.xml'

  social:
    - name: GitHub
      icon: github
      url: 'https://github.com/meashiri'
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 5
    - name: Tags
      url: /tags
      weight: 3
    - name: Categories
      url: /categories
      weight: 4
